/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mailmanager;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;

/**
 *
 * @author Vector
 */
public class Inbox extends javax.swing.JFrame {

    public static final Map<Integer, Vector> emails = new HashMap<Integer, Vector>();
    

    /**
     * Creates new form Inbox
     */
    /*Vector data
     1. Email Content.
     2. From
     3. Sent Date
     4. Subject

     */
    
    //getCount returns the total number of emails in Inbox. Emails are read from newer to old.
    //So if count = 10, email with id of 10 is the newest email in the inbox.
    
     public static int selectedEmail = 0;
    public Inbox() throws MessagingException {
     
       
        
        initComponents();
                  String text = "Inbox";
        jLabel1.setText("<html><div style=\"text-align: center;\">" + text + "</html>");

 
    
        
        ReadEmail readObj = new ReadEmail();
        Config conf = Config.getInstance();
        int startPoint = readObj.getCount();
         ArrayList<Email> emails = readObj.readEmails(startPoint);
        
         
         String[] strings = readObj.getSenders(startPoint);
       
         jList1.setListData(strings);


         

    }
     
  
        
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator13 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        subject10 = new javax.swing.JLabel();
        subject1 = new javax.swing.JLabel();
        subject2 = new javax.swing.JLabel();
        subject3 = new javax.swing.JLabel();
        subject4 = new javax.swing.JLabel();
        subject5 = new javax.swing.JLabel();
        subject6 = new javax.swing.JLabel();
        subject7 = new javax.swing.JLabel();
        subject8 = new javax.swing.JLabel();
        subject9 = new javax.swing.JLabel();
        date10 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        date5 = new javax.swing.JLabel();
        date6 = new javax.swing.JLabel();
        date7 = new javax.swing.JLabel();
        date8 = new javax.swing.JLabel();
        date9 = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        jSeparator29 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Inbox");

        jLayeredPane1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Sender");
        jLabel2.setBounds(30, 20, 60, 14);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Subject");
        jLabel3.setBounds(250, 20, 60, 14);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Date");
        jLabel4.setBounds(540, 20, 27, 14);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        filler1.setBounds(210, 80, 0, 0);
        jLayeredPane1.add(filler1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator1.setBounds(0, 160, 480, 0);
        jLayeredPane1.add(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSeparator2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSeparator2MouseClicked(evt);
            }
        });
        jSeparator2.setBounds(0, 40, 680, 10);
        jLayeredPane1.add(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator3.setBounds(0, 70, 680, 10);
        jLayeredPane1.add(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator4.setBounds(0, 100, 680, 10);
        jLayeredPane1.add(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator6.setBounds(0, 160, 480, 0);
        jLayeredPane1.add(jSeparator6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator7.setBounds(0, 160, 480, 0);
        jLayeredPane1.add(jSeparator7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator8.setBounds(0, 160, 480, 0);
        jLayeredPane1.add(jSeparator8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator9.setBounds(0, 160, 480, 0);
        jLayeredPane1.add(jSeparator9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator10.setBounds(0, 160, 480, 0);
        jLayeredPane1.add(jSeparator10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator11.setBounds(0, 160, 480, 0);
        jLayeredPane1.add(jSeparator11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator12.setBounds(-10, 130, 680, 10);
        jLayeredPane1.add(jSeparator12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator14.setBounds(0, 340, 680, 10);
        jLayeredPane1.add(jSeparator14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator15.setBounds(0, 160, 480, 10);
        jLayeredPane1.add(jSeparator15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator17.setBounds(0, 260, 0, 2);
        jLayeredPane1.add(jSeparator17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator19.setBounds(0, 282, 460, 0);
        jLayeredPane1.add(jSeparator19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Next >>");
        jButton1.setBounds(30, 360, 610, 23);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject10.setText("jLabel15");
        subject10.setBounds(250, 320, 170, 14);
        jLayeredPane1.add(subject10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject1.setText("jLabel15");
        subject1.setBounds(250, 50, 170, 14);
        jLayeredPane1.add(subject1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject2.setText("jLabel15");
        subject2.setBounds(250, 80, 170, 14);
        jLayeredPane1.add(subject2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject3.setText("jLabel15");
        subject3.setBounds(250, 110, 170, 14);
        jLayeredPane1.add(subject3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject4.setText("jLabel15");
        subject4.setBounds(250, 140, 170, 14);
        jLayeredPane1.add(subject4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject5.setText("jLabel15");
        subject5.setBounds(250, 170, 170, 14);
        jLayeredPane1.add(subject5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject6.setText("jLabel15");
        subject6.setBounds(250, 200, 170, 14);
        jLayeredPane1.add(subject6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject7.setText("jLabel15");
        subject7.setBounds(250, 230, 170, 14);
        jLayeredPane1.add(subject7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject8.setText("jLabel15");
        subject8.setBounds(250, 260, 170, 14);
        jLayeredPane1.add(subject8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject9.setText("jLabel15");
        subject9.setBounds(250, 290, 170, 14);
        jLayeredPane1.add(subject9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        date10.setText("jLabel25");
        date10.setBounds(540, 320, 80, 14);
        jLayeredPane1.add(date10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        date1.setText("jLabel25");
        date1.setBounds(540, 50, 80, 14);
        jLayeredPane1.add(date1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        date2.setText("jLabel25");
        date2.setBounds(540, 80, 80, 14);
        jLayeredPane1.add(date2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        date3.setText("jLabel25");
        date3.setBounds(540, 110, 80, 14);
        jLayeredPane1.add(date3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        date4.setText("jLabel25");
        date4.setBounds(540, 140, 80, 14);
        jLayeredPane1.add(date4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        date5.setText("jLabel25");
        date5.setBounds(540, 170, 80, 14);
        jLayeredPane1.add(date5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        date6.setText("jLabel25");
        date6.setBounds(540, 200, 80, 14);
        jLayeredPane1.add(date6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        date7.setText("jLabel25");
        date7.setBounds(540, 230, 80, 14);
        jLayeredPane1.add(date7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        date8.setText("jLabel25");
        date8.setBounds(540, 260, 80, 14);
        jLayeredPane1.add(date8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        date9.setText("jLabel25");
        date9.setBounds(540, 290, 80, 14);
        jLayeredPane1.add(date9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator24.setBounds(0, 160, 680, 10);
        jLayeredPane1.add(jSeparator24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator25.setBounds(0, 190, 680, 10);
        jLayeredPane1.add(jSeparator25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator26.setBounds(0, 220, 680, 10);
        jLayeredPane1.add(jSeparator26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator27.setBounds(0, 250, 680, 10);
        jLayeredPane1.add(jSeparator27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator28.setBounds(0, 280, 680, 10);
        jLayeredPane1.add(jSeparator28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator29.setBounds(0, 310, 680, 10);
        jLayeredPane1.add(jSeparator29, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jScrollPane1.setBounds(25, 40, 200, 300);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSeparator2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSeparator2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jSeparator2MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
                 selectedEmail = jList1.getSelectedIndex();
                 this.setVisible(false);
                 ViewMessage obj = new ViewMessage();
                 System.out.println("Createed ViewMessage Object.");
                 obj.setVisible(true);
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Inbox().setVisible(true);
                } catch (MessagingException ex) {
                    Logger.getLogger(Inbox.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date10;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JLabel date5;
    private javax.swing.JLabel date6;
    private javax.swing.JLabel date7;
    private javax.swing.JLabel date8;
    private javax.swing.JLabel date9;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel subject1;
    private javax.swing.JLabel subject10;
    private javax.swing.JLabel subject2;
    private javax.swing.JLabel subject3;
    private javax.swing.JLabel subject4;
    private javax.swing.JLabel subject5;
    private javax.swing.JLabel subject6;
    private javax.swing.JLabel subject7;
    private javax.swing.JLabel subject8;
    private javax.swing.JLabel subject9;
    // End of variables declaration//GEN-END:variables
}
